#include <bits/stdc++.h>
using namespace std;
#define fin '\n'
const int maxn = 1e2;
typedef pair<int,int> pi;
int grid[maxn][maxn];
bool vis[maxn][maxn];
int main() {
    ios_base::sync_with_stdio(0);cin.tie(NULL);cout.tie(NULL);
    int r,c; cin>>r>>c;
    int sx, sy; cin>>sx>>sy;
    pi st = {sx,sy};
    memset(grid,0,sizeof(grid));
    for(int i=0; i<r; i++) {
        for(int j=0; j<c; j++) {
            char tmp; cin>>tmp;
            if(tmp=='T') grid[i][j] = 1;
        }
    }
    queue <pi> q;
    q.push(st);
    int moves[4][2] = {{1,0},{-1,0},{0,1},{0,-1}};
    while(!q.empty()) {
        pi u = q.front(); q.pop();
        int i = u.first, j = u.second; vis[i][j] = 1; grid[i][j] = 1;
        for(int k=0; k<4; k++) {
            int ni = i+moves[k][1], nj=j+moves[k][0];
            if(grid[ni][nj]) continue;
            else {
                if(!vis[ni][nj]) {
                    q.push({ni,nj}); vis[ni][nj] = 1;
                }
            }
        }
    }
    cout<<fin;
    for(int i=0; i<r; i++) {
        for(int j=0; j<c; j++) {
            if(!grid[i][j]) cout<<'.';
            else cout<<'T';
        } cout<<'\n';
    }
}

/*

.....TTTTTTT............................
....T.......TTTTTTTTTTTT................
...T....................TTTT............
....T......................T............
..TT.....................TT.............
.T.......................T..............
..T.......................TTT...........
...TT........................T..........
.....T........................T.........
.....T.....TT.................T.........
.....T...TT..TT..............T..........
....T....T.....T..........TTT...........
...T......T....TTT....TTTT..............
....T......T.....TTTTT..................
.....TTTTTT.............................

.....TTTTTTT.......................
....T.......TTTTTTTTTTTT...........
...T....................TTTT.......
....T......................T.......
..TT......TTTTTTT........TT........
.T.......T.......T.......T.........
..T......T........T.......TTT......
...TT.....TTTTTTTT...........T.....
.....T........................T....
.....T.....TT.................T....
.....T...TT..TT..............T.....
....T....T.....T..........TTT......
...T......T....TTT....TTTT.........
....T......T.....TTTTT.............
.....TTTTTT........................
*/
